### ISSUE TITLE
readme.mdの編集

### ISSUE THREAD

**Issue by shinsato28** [TEAM-D-Okome/nagano_cake#85]

**Comment by shinsato28** [comment]
![スクリーンショット (18)](https://user-images.githubusercontent.com/125238969/233819598-dab3f3cb-1b96-4615-9d72-3a5dafdbea26.png)

**Comment by shinsato28** [comment]
![スクリーンショット (18)](https://user-images.githubusercontent.com/125238969/233819609-53e4cfb7-4253-4f2f-b90c-1e4009d751a7.png)

**Comment by shinsato28** [comment]
![naganocake_logo](https://user-images.githubusercontent.com/125238969/233820830-423a4af0-fa90-4242-8d3f-5698a27c8d68.jpg)

**Comment by shinsato28** [comment]
![ながのCAKE ER図 drawio](https://user-images.githubusercontent.com/125238969/233821147-ca5aad01-8867-4a16-9849-a053616ba589.png)

**Comment by yk-kc** [comment]
![ロゴ案④](https://user-images.githubusercontent.com/124197100/233823099-3ffbda49-6549-4902-9a04-5b2f4c10ac1e.png)

**Comment by shinsato28** [comment]
![ながのCAKE ER図 drawio (2)](https://user-images.githubusercontent.com/125238969/233823460-5f27089b-42ec-4b5b-9bf6-6009de170942.png)

**Comment by shinsato28** [comment]
![ながのCAKE ER図 drawio (1)](https://user-images.githubusercontent.com/125238969/233823470-d8b718f0-e0be-4f64-a502-fb5a227f6ee8.png)

**Comment by shinsato28** [comment]
![スクリーンショット (20)](https://user-images.githubusercontent.com/125238969/233879062-218dc306-c374-41ed-82e5-accc8457d589.png)

**Comment by yk-kc** [comment]
![スクリーンショット 2023-04-24 123838](https://user-images.githubusercontent.com/124197100/233895043-8f4ea4aa-e4ca-4cf0-ba1a-0c024303fcb9.png)
